name: Nightly Build 2

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
      - name: "Build and test"
        shell: bash
        run: /usr/bin/date
